// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace PropertEase_Commends
{
    public partial class PropertyValuePrediction
    {
        /// <summary>
        /// model input class for PropertyValuePrediction.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Id")]
            public float Id { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"Area")]
            public string Area { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Quality")]
            public string Quality { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Latitude")]
            public float Latitude { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Longitude")]
            public float Longitude { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Price")]
            public float Price { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"SizeInSqft")]
            public float SizeInSqft { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"PricePerSqft")]
            public float PricePerSqft { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"NoOfBedrooms")]
            public float NoOfBedrooms { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"NoOfBathrooms")]
            public float NoOfBathrooms { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"MaidRoom")]
            public bool MaidRoom { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"UnFurnished")]
            public bool UnFurnished { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"Balcony")]
            public bool Balcony { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"BarbecueArea")]
            public bool BarbecueArea { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"BuiltInWardrobes")]
            public bool BuiltInWardrobes { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"CentralAc")]
            public bool CentralAc { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"ChildrensPlayArea")]
            public bool ChildrensPlayArea { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"ChildrensPool")]
            public bool ChildrensPool { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"Concierge")]
            public bool Concierge { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"CoveredParking")]
            public bool CoveredParking { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"KitchenAppliances")]
            public bool KitchenAppliances { get; set; }

            [LoadColumn(21)]
            [ColumnName(@"LobbyInBuilding")]
            public bool LobbyInBuilding { get; set; }

            [LoadColumn(22)]
            [ColumnName(@"MaidService")]
            public bool MaidService { get; set; }

            [LoadColumn(23)]
            [ColumnName(@"Networked")]
            public bool Networked { get; set; }

            [LoadColumn(24)]
            [ColumnName(@"PetsAllowed")]
            public bool PetsAllowed { get; set; }

            [LoadColumn(25)]
            [ColumnName(@"PrivateGarden")]
            public bool PrivateGarden { get; set; }

            [LoadColumn(26)]
            [ColumnName(@"PrivateGym")]
            public bool PrivateGym { get; set; }

            [LoadColumn(27)]
            [ColumnName(@"PrivateJacuzzi")]
            public bool PrivateJacuzzi { get; set; }

            [LoadColumn(28)]
            [ColumnName(@"PrivatePool")]
            public bool PrivatePool { get; set; }

            [LoadColumn(29)]
            [ColumnName(@"Security")]
            public bool Security { get; set; }

            [LoadColumn(30)]
            [ColumnName(@"SharedGym")]
            public bool SharedGym { get; set; }

            [LoadColumn(31)]
            [ColumnName(@"Study")]
            public bool Study { get; set; }

            [LoadColumn(32)]
            [ColumnName(@"SharedPool")]
            public bool SharedPool { get; set; }

            [LoadColumn(33)]
            [ColumnName(@"SharedSpa")]
            public bool SharedSpa { get; set; }

            [LoadColumn(34)]
            [ColumnName(@"VastuCompliant")]
            public bool VastuCompliant { get; set; }

            [LoadColumn(35)]
            [ColumnName(@"ViewOfLandmark")]
            public bool ViewOfLandmark { get; set; }

            [LoadColumn(36)]
            [ColumnName(@"ViewOfWater")]
            public bool ViewOfWater { get; set; }

            [LoadColumn(37)]
            [ColumnName(@"WalkInCloset")]
            public bool WalkInCloset { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for PropertyValuePrediction.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Id")]
            public float Id { get; set; }

            [ColumnName(@"Area")]
            public float[] Area { get; set; }

            [ColumnName(@"Quality")]
            public float[] Quality { get; set; }

            [ColumnName(@"Latitude")]
            public float Latitude { get; set; }

            [ColumnName(@"Longitude")]
            public float Longitude { get; set; }

            [ColumnName(@"Price")]
            public float Price { get; set; }

            [ColumnName(@"SizeInSqft")]
            public float SizeInSqft { get; set; }

            [ColumnName(@"PricePerSqft")]
            public float PricePerSqft { get; set; }

            [ColumnName(@"NoOfBedrooms")]
            public float NoOfBedrooms { get; set; }

            [ColumnName(@"NoOfBathrooms")]
            public float NoOfBathrooms { get; set; }

            [ColumnName(@"MaidRoom")]
            public float[] MaidRoom { get; set; }

            [ColumnName(@"UnFurnished")]
            public float[] UnFurnished { get; set; }

            [ColumnName(@"Balcony")]
            public float[] Balcony { get; set; }

            [ColumnName(@"BarbecueArea")]
            public float[] BarbecueArea { get; set; }

            [ColumnName(@"BuiltInWardrobes")]
            public float[] BuiltInWardrobes { get; set; }

            [ColumnName(@"CentralAc")]
            public float[] CentralAc { get; set; }

            [ColumnName(@"ChildrensPlayArea")]
            public float[] ChildrensPlayArea { get; set; }

            [ColumnName(@"ChildrensPool")]
            public float[] ChildrensPool { get; set; }

            [ColumnName(@"Concierge")]
            public float[] Concierge { get; set; }

            [ColumnName(@"CoveredParking")]
            public float[] CoveredParking { get; set; }

            [ColumnName(@"KitchenAppliances")]
            public float[] KitchenAppliances { get; set; }

            [ColumnName(@"LobbyInBuilding")]
            public float[] LobbyInBuilding { get; set; }

            [ColumnName(@"MaidService")]
            public float[] MaidService { get; set; }

            [ColumnName(@"Networked")]
            public float[] Networked { get; set; }

            [ColumnName(@"PetsAllowed")]
            public float[] PetsAllowed { get; set; }

            [ColumnName(@"PrivateGarden")]
            public float[] PrivateGarden { get; set; }

            [ColumnName(@"PrivateGym")]
            public float[] PrivateGym { get; set; }

            [ColumnName(@"PrivateJacuzzi")]
            public float[] PrivateJacuzzi { get; set; }

            [ColumnName(@"PrivatePool")]
            public float[] PrivatePool { get; set; }

            [ColumnName(@"Security")]
            public float[] Security { get; set; }

            [ColumnName(@"SharedGym")]
            public float[] SharedGym { get; set; }

            [ColumnName(@"Study")]
            public float[] Study { get; set; }

            [ColumnName(@"SharedPool")]
            public float[] SharedPool { get; set; }

            [ColumnName(@"SharedSpa")]
            public float[] SharedSpa { get; set; }

            [ColumnName(@"VastuCompliant")]
            public float[] VastuCompliant { get; set; }

            [ColumnName(@"ViewOfLandmark")]
            public float[] ViewOfLandmark { get; set; }

            [ColumnName(@"ViewOfWater")]
            public float[] ViewOfWater { get; set; }

            [ColumnName(@"WalkInCloset")]
            public float[] WalkInCloset { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("PropertyValuePrediction.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
