// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropertEase_Database.SQLConnection;

#nullable disable

namespace PropertEase_Database.Migrations
{
    [DbContext(typeof(PropertEaseDbContext))]
    partial class PropertEaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropertEase_Models.Models.Core.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Balcony")
                        .HasColumnType("bit");

                    b.Property<bool>("BarbecueArea")
                        .HasColumnType("bit");

                    b.Property<bool>("BuiltInWardrobes")
                        .HasColumnType("bit");

                    b.Property<bool>("CentralAc")
                        .HasColumnType("bit");

                    b.Property<bool>("ChildrensPlayArea")
                        .HasColumnType("bit");

                    b.Property<bool>("ChildrensPool")
                        .HasColumnType("bit");

                    b.Property<bool>("Concierge")
                        .HasColumnType("bit");

                    b.Property<bool>("CoveredParking")
                        .HasColumnType("bit");

                    b.Property<bool>("KitchenAppliances")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<bool>("LobbyInBuilding")
                        .HasColumnType("bit");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<bool>("MaidRoom")
                        .HasColumnType("bit");

                    b.Property<bool>("MaidService")
                        .HasColumnType("bit");

                    b.Property<bool>("Networked")
                        .HasColumnType("bit");

                    b.Property<int>("NoOfBathrooms")
                        .HasColumnType("int");

                    b.Property<int>("NoOfBedrooms")
                        .HasColumnType("int");

                    b.Property<bool>("PetsAllowed")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<double>("PricePerSqft")
                        .HasColumnType("float");

                    b.Property<bool>("PrivateGarden")
                        .HasColumnType("bit");

                    b.Property<bool>("PrivateGym")
                        .HasColumnType("bit");

                    b.Property<bool>("PrivateJacuzzi")
                        .HasColumnType("bit");

                    b.Property<bool>("PrivatePool")
                        .HasColumnType("bit");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Security")
                        .HasColumnType("bit");

                    b.Property<bool>("SharedGym")
                        .HasColumnType("bit");

                    b.Property<bool>("SharedPool")
                        .HasColumnType("bit");

                    b.Property<bool>("SharedSpa")
                        .HasColumnType("bit");

                    b.Property<int>("SizeInSqft")
                        .HasColumnType("int");

                    b.Property<bool>("Study")
                        .HasColumnType("bit");

                    b.Property<bool>("UnFurnished")
                        .HasColumnType("bit");

                    b.Property<bool>("VastuCompliant")
                        .HasColumnType("bit");

                    b.Property<bool>("ViewOfLandmark")
                        .HasColumnType("bit");

                    b.Property<bool>("ViewOfWater")
                        .HasColumnType("bit");

                    b.Property<bool>("WalkInCloset")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
